/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Activity
     */
    type: ActivityTypeEnum;
    /**
     * ID de la page ou de l'élément concerné
     * @type {string}
     * @memberof Activity
     */
    targetId: string;
    /**
     * 
     * @type {Date}
     * @memberof Activity
     */
    createdAt: Date;
    /**
     * Description de l'activité (ex: Vous avez aimé la page de Mohamed)
     * @type {string}
     * @memberof Activity
     */
    description: string;
}


/**
 * @export
 */
export const ActivityTypeEnum = {
    Like: 'like',
    Comment: 'comment',
    Save: 'save',
    Follow: 'follow',
    Repost: 'repost',
    Quote: 'quote'
} as const;
export type ActivityTypeEnum = typeof ActivityTypeEnum[keyof typeof ActivityTypeEnum];


/**
 * Check if a given object implements the Activity interface.
 */
export function instanceOfActivity(value: object): value is Activity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('targetId' in value) || value['targetId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'type': json['type'],
        'targetId': json['targetId'],
        'createdAt': (new Date(json['createdAt'])),
        'description': json['description'],
    };
}

export function ActivityToJSON(json: any): Activity {
    return ActivityToJSONTyped(json, false);
}

export function ActivityToJSONTyped(value?: Activity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'type': value['type'],
        'targetId': value['targetId'],
        'createdAt': ((value['createdAt']).toISOString()),
        'description': value['description'],
    };
}

