/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentInput
 */
export interface CommentInput {
    /**
     * 
     * @type {string}
     * @memberof CommentInput
     */
    content: string;
}

/**
 * Check if a given object implements the CommentInput interface.
 */
export function instanceOfCommentInput(value: object): value is CommentInput {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CommentInputFromJSON(json: any): CommentInput {
    return CommentInputFromJSONTyped(json, false);
}

export function CommentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentInput {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function CommentInputToJSON(json: any): CommentInput {
    return CommentInputToJSONTyped(json, false);
}

export function CommentInputToJSONTyped(value?: CommentInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

