/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    pageId: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    authorId: string;
    /**
     * 
     * @type {User}
     * @memberof Comment
     */
    author: User;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof Comment
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('pageId' in value) || value['pageId'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pageId': json['pageId'],
        'authorId': json['authorId'],
        'author': UserFromJSON(json['author']),
        'content': json['content'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CommentToJSON(json: any): Comment {
    return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(value?: Comment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'pageId': value['pageId'],
        'authorId': value['authorId'],
        'author': UserToJSON(value['author']),
        'content': value['content'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

