/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Comment
 */
export interface Comment {
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Comment
   */
  authorId?: string;
  /**
   *
   * @type {Date}
   * @memberof Comment
   */
  createdAt?: Date;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): value is Comment {
  if (!('content' in value) || value['content'] === undefined) return false;
  return true;
}

export function CommentFromJSON(json: any): Comment {
  return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Comment {
  if (json == null) {
    return json;
  }
  return {
    content: json['content'],
    id: json['id'] == null ? undefined : json['id'],
    authorId: json['authorId'] == null ? undefined : json['authorId'],
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
  };
}

export function CommentToJSON(json: any): Comment {
  return CommentToJSONTyped(json, false);
}

export function CommentToJSONTyped(
  value?: Comment | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    content: value['content'],
    id: value['id'],
    authorId: value['authorId'],
    createdAt:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
  };
}
