/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSessionRequest
 */
export interface CreateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    ip: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    userAgent?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    referer?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the CreateSessionRequest interface.
 */
export function instanceOfCreateSessionRequest(value: object): value is CreateSessionRequest {
    if (!('ip' in value) || value['ip'] === undefined) return false;
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    return true;
}

export function CreateSessionRequestFromJSON(json: any): CreateSessionRequest {
    return CreateSessionRequestFromJSONTyped(json, false);
}

export function CreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ip': json['ip'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'referer': json['referer'] == null ? undefined : json['referer'],
        'sessionId': json['sessionId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function CreateSessionRequestToJSON(json: any): CreateSessionRequest {
    return CreateSessionRequestToJSONTyped(json, false);
}

export function CreateSessionRequestToJSONTyped(value?: CreateSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ip': value['ip'],
        'userAgent': value['userAgent'],
        'referer': value['referer'],
        'sessionId': value['sessionId'],
        'userId': value['userId'],
    };
}

