/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentInput } from './CommentInput';
import {
  CommentInputFromJSON,
  CommentInputFromJSONTyped,
  CommentInputToJSON,
  CommentInputToJSONTyped,
} from './CommentInput';

/**
 *
 * @export
 * @interface EndPage
 */
export interface EndPage {
  /**
   *
   * @type {string}
   * @memberof EndPage
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof EndPage
   */
  content: string;
  /**
   *
   * @type {string}
   * @memberof EndPage
   */
  tone: EndPageToneEnum;
  /**
   *
   * @type {Array<string>}
   * @memberof EndPage
   */
  gifUrls?: Array<string>;
  /**
   *
   * @type {string}
   * @memberof EndPage
   */
  soundUrl?: string;
  /**
   *
   * @type {boolean}
   * @memberof EndPage
   */
  isPublic?: boolean;
  /**
   *
   * @type {string}
   * @memberof EndPage
   */
  authorId: string;
  /**
   *
   * @type {Array<CommentInput>}
   * @memberof EndPage
   */
  comments?: Array<CommentInput>;
  /**
   *
   * @type {string}
   * @memberof EndPage
   */
  id?: string;
  /**
   *
   * @type {Date}
   * @memberof EndPage
   */
  createdAt?: Date;
}

/**
 * @export
 */
export const EndPageToneEnum = {
  Dramatic: 'dramatic',
  Ironic: 'ironic',
  Cringe: 'cringe',
  Classy: 'classy',
  Touching: 'touching',
  Absurd: 'absurd',
  PassiveAggressive: 'passive_aggressive',
  Honest: 'honest',
} as const;
export type EndPageToneEnum =
  (typeof EndPageToneEnum)[keyof typeof EndPageToneEnum];

/**
 * Check if a given object implements the EndPage interface.
 */
export function instanceOfEndPage(value: object): value is EndPage {
  if (!('title' in value) || value['title'] === undefined) return false;
  if (!('content' in value) || value['content'] === undefined) return false;
  if (!('tone' in value) || value['tone'] === undefined) return false;
  if (!('authorId' in value) || value['authorId'] === undefined) return false;
  return true;
}

export function EndPageFromJSON(json: any): EndPage {
  return EndPageFromJSONTyped(json, false);
}

export function EndPageFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EndPage {
  if (json == null) {
    return json;
  }
  return {
    title: json['title'],
    content: json['content'],
    tone: json['tone'],
    gifUrls: json['gifUrls'] == null ? undefined : json['gifUrls'],
    soundUrl: json['soundUrl'] == null ? undefined : json['soundUrl'],
    isPublic: json['isPublic'] == null ? undefined : json['isPublic'],
    authorId: json['authorId'],
    comments:
      json['comments'] == null
        ? undefined
        : (json['comments'] as Array<any>).map(CommentInputFromJSON),
    id: json['id'] == null ? undefined : json['id'],
    createdAt:
      json['createdAt'] == null ? undefined : new Date(json['createdAt']),
  };
}

export function EndPageToJSON(json: any): EndPage {
  return EndPageToJSONTyped(json, false);
}

export function EndPageToJSONTyped(
  value?: EndPage | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    title: value['title'],
    content: value['content'],
    tone: value['tone'],
    gifUrls: value['gifUrls'],
    soundUrl: value['soundUrl'],
    isPublic: value['isPublic'],
    authorId: value['authorId'],
    comments:
      value['comments'] == null
        ? undefined
        : (value['comments'] as Array<any>).map(CommentInputToJSON),
    id: value['id'],
    createdAt:
      value['createdAt'] == null ? undefined : value['createdAt'].toISOString(),
  };
}
