/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface EndPage
 */
export interface EndPage {
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    tone: EndPageToneEnum;
    /**
     * URL de l'image de la page
     * @type {string}
     * @memberof EndPage
     */
    image?: string | null;
    /**
     * Liste des hashtags associés au post
     * @type {Array<string>}
     * @memberof EndPage
     */
    hashtags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof EndPage
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    authorId: string;
    /**
     * 
     * @type {User}
     * @memberof EndPage
     */
    author: User;
    /**
     * Indique si la page est dans le Hall of Fame
     * @type {boolean}
     * @memberof EndPage
     */
    hallOfFame: boolean;
    /**
     * Nombre de likes sur la page
     * @type {number}
     * @memberof EndPage
     */
    likes: number;
    /**
     * Indique si l'utilisateur connecté a aimé la page
     * @type {boolean}
     * @memberof EndPage
     */
    liked: boolean;
    /**
     * Indique si l'utilisateur connecté a sauvegardé la page
     * @type {boolean}
     * @memberof EndPage
     */
    saved: boolean;
    /**
     * Nombre de commentaires sur la page
     * @type {number}
     * @memberof EndPage
     */
    commentsCount: number;
    /**
     * Nombre de reposts de la page
     * @type {number}
     * @memberof EndPage
     */
    reposts: number;
    /**
     * Liste des posts qui citent cette page
     * @type {Array<EndPage>}
     * @memberof EndPage
     */
    quotes?: Array<EndPage>;
    /**
     * ID du post original en cas de repost ou de citation
     * @type {string}
     * @memberof EndPage
     */
    originalPostId?: string | null;
    /**
     * 
     * @type {EndPage}
     * @memberof EndPage
     */
    originalPost?: EndPage;
    /**
     * Score d'éligibilité pour le Hall of Fame
     * @type {number}
     * @memberof EndPage
     */
    score: number;
}


/**
 * @export
 */
export const EndPageToneEnum = {
    Dramatic: 'dramatic',
    Ironic: 'ironic',
    Cringe: 'cringe',
    Classy: 'classy',
    Touching: 'touching',
    Absurd: 'absurd',
    PassiveAggressive: 'passive_aggressive',
    Honest: 'honest'
} as const;
export type EndPageToneEnum = typeof EndPageToneEnum[keyof typeof EndPageToneEnum];


/**
 * Check if a given object implements the EndPage interface.
 */
export function instanceOfEndPage(value: object): value is EndPage {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tone' in value) || value['tone'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('hallOfFame' in value) || value['hallOfFame'] === undefined) return false;
    if (!('likes' in value) || value['likes'] === undefined) return false;
    if (!('liked' in value) || value['liked'] === undefined) return false;
    if (!('saved' in value) || value['saved'] === undefined) return false;
    if (!('commentsCount' in value) || value['commentsCount'] === undefined) return false;
    if (!('reposts' in value) || value['reposts'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function EndPageFromJSON(json: any): EndPage {
    return EndPageFromJSONTyped(json, false);
}

export function EndPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndPage {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'tone': json['tone'],
        'image': json['image'] == null ? undefined : json['image'],
        'hashtags': json['hashtags'] == null ? undefined : json['hashtags'],
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'authorId': json['authorId'],
        'author': UserFromJSON(json['author']),
        'hallOfFame': json['hallOfFame'],
        'likes': json['likes'],
        'liked': json['liked'],
        'saved': json['saved'],
        'commentsCount': json['commentsCount'],
        'reposts': json['reposts'],
        'quotes': json['quotes'] == null ? undefined : ((json['quotes'] as Array<any>).map(EndPageFromJSON)),
        'originalPostId': json['originalPostId'] == null ? undefined : json['originalPostId'],
        'originalPost': json['originalPost'] == null ? undefined : EndPageFromJSON(json['originalPost']),
        'score': json['score'],
    };
}

export function EndPageToJSON(json: any): EndPage {
    return EndPageToJSONTyped(json, false);
}

export function EndPageToJSONTyped(value?: EndPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'tone': value['tone'],
        'image': value['image'],
        'hashtags': value['hashtags'],
        'id': value['id'],
        'createdAt': ((value['createdAt']).toISOString()),
        'authorId': value['authorId'],
        'author': UserToJSON(value['author']),
        'hallOfFame': value['hallOfFame'],
        'likes': value['likes'],
        'liked': value['liked'],
        'saved': value['saved'],
        'commentsCount': value['commentsCount'],
        'reposts': value['reposts'],
        'quotes': value['quotes'] == null ? undefined : ((value['quotes'] as Array<any>).map(EndPageToJSON)),
        'originalPostId': value['originalPostId'],
        'originalPost': EndPageToJSON(value['originalPost']),
        'score': value['score'],
    };
}

