/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EndPage
 */
export interface EndPage {
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    tone: EndPageToneEnum;
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof EndPage
     */
    createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof EndPage
     */
    authorId?: string;
    /**
     * Indique si la page est dans le Hall of Fame
     * @type {boolean}
     * @memberof EndPage
     */
    hallOfFame?: boolean;
}


/**
 * @export
 */
export const EndPageToneEnum = {
    Dramatic: 'dramatic',
    Ironic: 'ironic',
    Cringe: 'cringe',
    Classy: 'classy',
    Touching: 'touching',
    Absurd: 'absurd',
    PassiveAggressive: 'passive_aggressive',
    Honest: 'honest'
} as const;
export type EndPageToneEnum = typeof EndPageToneEnum[keyof typeof EndPageToneEnum];


/**
 * Check if a given object implements the EndPage interface.
 */
export function instanceOfEndPage(value: object): value is EndPage {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tone' in value) || value['tone'] === undefined) return false;
    return true;
}

export function EndPageFromJSON(json: any): EndPage {
    return EndPageFromJSONTyped(json, false);
}

export function EndPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndPage {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'tone': json['tone'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'authorId': json['authorId'] == null ? undefined : json['authorId'],
        'hallOfFame': json['hallOfFame'] == null ? undefined : json['hallOfFame'],
    };
}

export function EndPageToJSON(json: any): EndPage {
    return EndPageToJSONTyped(json, false);
}

export function EndPageToJSONTyped(value?: EndPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'tone': value['tone'],
        'id': value['id'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'authorId': value['authorId'],
        'hallOfFame': value['hallOfFame'],
    };
}

