/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommentInput } from './CommentInput';
import {
    CommentInputFromJSON,
    CommentInputFromJSONTyped,
    CommentInputToJSON,
    CommentInputToJSONTyped,
} from './CommentInput';

/**
 * 
 * @export
 * @interface EndPageInput
 */
export interface EndPageInput {
    /**
     * 
     * @type {string}
     * @memberof EndPageInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EndPageInput
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof EndPageInput
     */
    tone: EndPageInputToneEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof EndPageInput
     */
    gifUrls?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EndPageInput
     */
    soundUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EndPageInput
     */
    isPublic?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EndPageInput
     */
    authorId: string;
    /**
     * 
     * @type {Array<CommentInput>}
     * @memberof EndPageInput
     */
    comments?: Array<CommentInput>;
}


/**
 * @export
 */
export const EndPageInputToneEnum = {
    Dramatic: 'dramatic',
    Ironic: 'ironic',
    Cringe: 'cringe',
    Classy: 'classy',
    Touching: 'touching',
    Absurd: 'absurd',
    PassiveAggressive: 'passive_aggressive',
    Honest: 'honest'
} as const;
export type EndPageInputToneEnum = typeof EndPageInputToneEnum[keyof typeof EndPageInputToneEnum];


/**
 * Check if a given object implements the EndPageInput interface.
 */
export function instanceOfEndPageInput(value: object): value is EndPageInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('tone' in value) || value['tone'] === undefined) return false;
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    return true;
}

export function EndPageInputFromJSON(json: any): EndPageInput {
    return EndPageInputFromJSONTyped(json, false);
}

export function EndPageInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndPageInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'content': json['content'],
        'tone': json['tone'],
        'gifUrls': json['gifUrls'] == null ? undefined : json['gifUrls'],
        'soundUrl': json['soundUrl'] == null ? undefined : json['soundUrl'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
        'authorId': json['authorId'],
        'comments': json['comments'] == null ? undefined : ((json['comments'] as Array<any>).map(CommentInputFromJSON)),
    };
}

export function EndPageInputToJSON(json: any): EndPageInput {
    return EndPageInputToJSONTyped(json, false);
}

export function EndPageInputToJSONTyped(value?: EndPageInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'content': value['content'],
        'tone': value['tone'],
        'gifUrls': value['gifUrls'],
        'soundUrl': value['soundUrl'],
        'isPublic': value['isPublic'],
        'authorId': value['authorId'],
        'comments': value['comments'] == null ? undefined : ((value['comments'] as Array<any>).map(CommentInputToJSON)),
    };
}

