/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EndPageInput
 */
export interface EndPageInput {
    /**
     * 
     * @type {string}
     * @memberof EndPageInput
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof EndPageInput
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof EndPageInput
     */
    tone: EndPageInputToneEnum;
}


/**
 * @export
 */
export const EndPageInputToneEnum = {
    Dramatic: 'dramatic',
    Ironic: 'ironic',
    Cringe: 'cringe',
    Classy: 'classy',
    Touching: 'touching',
    Absurd: 'absurd',
    PassiveAggressive: 'passive_aggressive',
    Honest: 'honest'
} as const;
export type EndPageInputToneEnum = typeof EndPageInputToneEnum[keyof typeof EndPageInputToneEnum];


/**
 * Check if a given object implements the EndPageInput interface.
 */
export function instanceOfEndPageInput(value: object): value is EndPageInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tone' in value) || value['tone'] === undefined) return false;
    return true;
}

export function EndPageInputFromJSON(json: any): EndPageInput {
    return EndPageInputFromJSONTyped(json, false);
}

export function EndPageInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndPageInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'tone': json['tone'],
    };
}

export function EndPageInputToJSON(json: any): EndPageInput {
    return EndPageInputToJSONTyped(json, false);
}

export function EndPageInputToJSONTyped(value?: EndPageInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'tone': value['tone'],
    };
}

