/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Follow
 */
export interface Follow {
    /**
     * 
     * @type {string}
     * @memberof Follow
     */
    followerId: string;
    /**
     * 
     * @type {string}
     * @memberof Follow
     */
    followingId: string;
    /**
     * 
     * @type {Date}
     * @memberof Follow
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Follow interface.
 */
export function instanceOfFollow(value: object): value is Follow {
    if (!('followerId' in value) || value['followerId'] === undefined) return false;
    if (!('followingId' in value) || value['followingId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function FollowFromJSON(json: any): Follow {
    return FollowFromJSONTyped(json, false);
}

export function FollowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Follow {
    if (json == null) {
        return json;
    }
    return {
        
        'followerId': json['followerId'],
        'followingId': json['followingId'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function FollowToJSON(json: any): Follow {
    return FollowToJSONTyped(json, false);
}

export function FollowToJSONTyped(value?: Follow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'followerId': value['followerId'],
        'followingId': value['followingId'],
        'createdAt': ((value['createdAt']).toISOString()),
    };
}

