/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GeolocationResponse
 */
export interface GeolocationResponse {
  /**
   *
   * @type {number}
   * @memberof GeolocationResponse
   */
  latitude?: number;
  /**
   *
   * @type {number}
   * @memberof GeolocationResponse
   */
  longitude?: number;
  /**
   *
   * @type {string}
   * @memberof GeolocationResponse
   */
  address?: string;
  /**
   *
   * @type {string}
   * @memberof GeolocationResponse
   */
  country?: string;
  /**
   *
   * @type {string}
   * @memberof GeolocationResponse
   */
  city?: string;
}

/**
 * Check if a given object implements the GeolocationResponse interface.
 */
export function instanceOfGeolocationResponse(
  value: object
): value is GeolocationResponse {
  return true;
}

export function GeolocationResponseFromJSON(json: any): GeolocationResponse {
  return GeolocationResponseFromJSONTyped(json, false);
}

export function GeolocationResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GeolocationResponse {
  if (json == null) {
    return json;
  }
  return {
    latitude: json['latitude'] == null ? undefined : json['latitude'],
    longitude: json['longitude'] == null ? undefined : json['longitude'],
    address: json['address'] == null ? undefined : json['address'],
    country: json['country'] == null ? undefined : json['country'],
    city: json['city'] == null ? undefined : json['city'],
  };
}

export function GeolocationResponseToJSON(json: any): GeolocationResponse {
  return GeolocationResponseToJSONTyped(json, false);
}

export function GeolocationResponseToJSONTyped(
  value?: GeolocationResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    latitude: value['latitude'],
    longitude: value['longitude'],
    address: value['address'],
    country: value['country'],
    city: value['city'],
  };
}
