/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeolocationRequest
 */
export interface GeolocationRequest {
    /**
     * 
     * @type {number}
     * @memberof GeolocationRequest
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof GeolocationRequest
     */
    longitude: number;
}

/**
 * Check if a given object implements the GeolocationRequest interface.
 */
export function instanceOfGeolocationRequest(value: object): value is GeolocationRequest {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function GeolocationRequestFromJSON(json: any): GeolocationRequest {
    return GeolocationRequestFromJSONTyped(json, false);
}

export function GeolocationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeolocationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
    };
}

export function GeolocationRequestToJSON(json: any): GeolocationRequest {
    return GeolocationRequestToJSONTyped(json, false);
}

export function GeolocationRequestToJSONTyped(value?: GeolocationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

