/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeolocationResponse
 */
export interface GeolocationResponse {
    /**
     * 
     * @type {string}
     * @memberof GeolocationResponse
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof GeolocationResponse
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof GeolocationResponse
     */
    region: string;
}

/**
 * Check if a given object implements the GeolocationResponse interface.
 */
export function instanceOfGeolocationResponse(value: object): value is GeolocationResponse {
    if (!('country' in value) || value['country'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    return true;
}

export function GeolocationResponseFromJSON(json: any): GeolocationResponse {
    return GeolocationResponseFromJSONTyped(json, false);
}

export function GeolocationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeolocationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'],
        'city': json['city'],
        'region': json['region'],
    };
}

export function GeolocationResponseToJSON(json: any): GeolocationResponse {
    return GeolocationResponseToJSONTyped(json, false);
}

export function GeolocationResponseToJSONTyped(value?: GeolocationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'city': value['city'],
        'region': value['region'],
    };
}

