/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHallOfFameScore200Response
 */
export interface GetHallOfFameScore200Response {
    /**
     * 
     * @type {string}
     * @memberof GetHallOfFameScore200Response
     */
    pageId?: string;
    /**
     * Score total basé sur réactions, commentaires, design et abonnement
     * @type {number}
     * @memberof GetHallOfFameScore200Response
     */
    score?: number;
    /**
     * Points pour les réactions (1 par réaction)
     * @type {number}
     * @memberof GetHallOfFameScore200Response
     */
    reactionsPoints?: number;
    /**
     * Points pour les commentaires (2 par commentaire)
     * @type {number}
     * @memberof GetHallOfFameScore200Response
     */
    commentsPoints?: number;
    /**
     * Points pour la qualité du design (1-3)
     * @type {number}
     * @memberof GetHallOfFameScore200Response
     */
    designPoints?: number;
    /**
     * Bonus d'abonnement (6 pour premium, 4 pour basic, 0 pour free)
     * @type {number}
     * @memberof GetHallOfFameScore200Response
     */
    subscriptionBonus?: number;
    /**
     * Indique si le score atteint le seuil minimum (10)
     * @type {boolean}
     * @memberof GetHallOfFameScore200Response
     */
    eligible?: boolean;
}

/**
 * Check if a given object implements the GetHallOfFameScore200Response interface.
 */
export function instanceOfGetHallOfFameScore200Response(value: object): value is GetHallOfFameScore200Response {
    return true;
}

export function GetHallOfFameScore200ResponseFromJSON(json: any): GetHallOfFameScore200Response {
    return GetHallOfFameScore200ResponseFromJSONTyped(json, false);
}

export function GetHallOfFameScore200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHallOfFameScore200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'pageId': json['pageId'] == null ? undefined : json['pageId'],
        'score': json['score'] == null ? undefined : json['score'],
        'reactionsPoints': json['reactionsPoints'] == null ? undefined : json['reactionsPoints'],
        'commentsPoints': json['commentsPoints'] == null ? undefined : json['commentsPoints'],
        'designPoints': json['designPoints'] == null ? undefined : json['designPoints'],
        'subscriptionBonus': json['subscriptionBonus'] == null ? undefined : json['subscriptionBonus'],
        'eligible': json['eligible'] == null ? undefined : json['eligible'],
    };
}

export function GetHallOfFameScore200ResponseToJSON(json: any): GetHallOfFameScore200Response {
    return GetHallOfFameScore200ResponseToJSONTyped(json, false);
}

export function GetHallOfFameScore200ResponseToJSONTyped(value?: GetHallOfFameScore200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pageId': value['pageId'],
        'score': value['score'],
        'reactionsPoints': value['reactionsPoints'],
        'commentsPoints': value['commentsPoints'],
        'designPoints': value['designPoints'],
        'subscriptionBonus': value['subscriptionBonus'],
        'eligible': value['eligible'],
    };
}

