/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSubscriptionBenefits200Response
 */
export interface GetSubscriptionBenefits200Response {
    /**
     * Nombre maximum de posts par jour
     * @type {number}
     * @memberof GetSubscriptionBenefits200Response
     */
    maxPosts?: number;
    /**
     * Nombre maximum de likes par jour
     * @type {number}
     * @memberof GetSubscriptionBenefits200Response
     */
    maxLikes?: number;
    /**
     * Accès aux fonctionnalités premium
     * @type {boolean}
     * @memberof GetSubscriptionBenefits200Response
     */
    premiumAccess?: boolean;
    /**
     * Accès au Hall of Fame
     * @type {boolean}
     * @memberof GetSubscriptionBenefits200Response
     */
    hallOfFameAccess?: boolean;
}

/**
 * Check if a given object implements the GetSubscriptionBenefits200Response interface.
 */
export function instanceOfGetSubscriptionBenefits200Response(value: object): value is GetSubscriptionBenefits200Response {
    return true;
}

export function GetSubscriptionBenefits200ResponseFromJSON(json: any): GetSubscriptionBenefits200Response {
    return GetSubscriptionBenefits200ResponseFromJSONTyped(json, false);
}

export function GetSubscriptionBenefits200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscriptionBenefits200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'maxPosts': json['maxPosts'] == null ? undefined : json['maxPosts'],
        'maxLikes': json['maxLikes'] == null ? undefined : json['maxLikes'],
        'premiumAccess': json['premiumAccess'] == null ? undefined : json['premiumAccess'],
        'hallOfFameAccess': json['hallOfFameAccess'] == null ? undefined : json['hallOfFameAccess'],
    };
}

export function GetSubscriptionBenefits200ResponseToJSON(json: any): GetSubscriptionBenefits200Response {
    return GetSubscriptionBenefits200ResponseToJSONTyped(json, false);
}

export function GetSubscriptionBenefits200ResponseToJSONTyped(value?: GetSubscriptionBenefits200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'maxPosts': value['maxPosts'],
        'maxLikes': value['maxLikes'],
        'premiumAccess': value['premiumAccess'],
        'hallOfFameAccess': value['hallOfFameAccess'],
    };
}

