/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSubscriptionStatus200Response
 */
export interface GetSubscriptionStatus200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetSubscriptionStatus200Response
     */
    subscribed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetSubscriptionStatus200Response
     */
    offerId?: string;
    /**
     * 
     * @type {Date}
     * @memberof GetSubscriptionStatus200Response
     */
    expiryDate?: Date;
}

/**
 * Check if a given object implements the GetSubscriptionStatus200Response interface.
 */
export function instanceOfGetSubscriptionStatus200Response(value: object): value is GetSubscriptionStatus200Response {
    return true;
}

export function GetSubscriptionStatus200ResponseFromJSON(json: any): GetSubscriptionStatus200Response {
    return GetSubscriptionStatus200ResponseFromJSONTyped(json, false);
}

export function GetSubscriptionStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscriptionStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'subscribed': json['subscribed'] == null ? undefined : json['subscribed'],
        'offerId': json['offerId'] == null ? undefined : json['offerId'],
        'expiryDate': json['expiryDate'] == null ? undefined : (new Date(json['expiryDate'])),
    };
}

export function GetSubscriptionStatus200ResponseToJSON(json: any): GetSubscriptionStatus200Response {
    return GetSubscriptionStatus200ResponseToJSONTyped(json, false);
}

export function GetSubscriptionStatus200ResponseToJSONTyped(value?: GetSubscriptionStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscribed': value['subscribed'],
        'offerId': value['offerId'],
        'expiryDate': value['expiryDate'] == null ? undefined : ((value['expiryDate']).toISOString()),
    };
}

