/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTrendingHashtags200ResponseInner
 */
export interface ListTrendingHashtags200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ListTrendingHashtags200ResponseInner
     */
    hashtag?: string;
    /**
     * 
     * @type {number}
     * @memberof ListTrendingHashtags200ResponseInner
     */
    count?: number;
}

/**
 * Check if a given object implements the ListTrendingHashtags200ResponseInner interface.
 */
export function instanceOfListTrendingHashtags200ResponseInner(value: object): value is ListTrendingHashtags200ResponseInner {
    return true;
}

export function ListTrendingHashtags200ResponseInnerFromJSON(json: any): ListTrendingHashtags200ResponseInner {
    return ListTrendingHashtags200ResponseInnerFromJSONTyped(json, false);
}

export function ListTrendingHashtags200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTrendingHashtags200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'hashtag': json['hashtag'] == null ? undefined : json['hashtag'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function ListTrendingHashtags200ResponseInnerToJSON(json: any): ListTrendingHashtags200ResponseInner {
    return ListTrendingHashtags200ResponseInnerToJSONTyped(json, false);
}

export function ListTrendingHashtags200ResponseInnerToJSONTyped(value?: ListTrendingHashtags200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashtag': value['hashtag'],
        'count': value['count'],
    };
}

