/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called -->
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LogoutUserRequest
 */
export interface LogoutUserRequest {
  /**
   *
   * @type {string}
   * @memberof LogoutUserRequest
   */
  refreshToken: string;
}

/**
 * Check if a given object implements the LogoutUserRequest interface.
 */
export function instanceOfLogoutUserRequest(
  value: object
): value is LogoutUserRequest {
  if (!('refreshToken' in value) || value['refreshToken'] === undefined)
    return false;
  return true;
}

export function LogoutUserRequestFromJSON(json: any): LogoutUserRequest {
  return LogoutUserRequestFromJSONTyped(json, false);
}

export function LogoutUserRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LogoutUserRequest {
  if (json == null) {
    return json;
  }
  return {
    refreshToken: json['refreshToken'],
  };
}

export function LogoutUserRequestToJSON(json: any): LogoutUserRequest {
  return LogoutUserRequestToJSONTyped(json, false);
}

export function LogoutUserRequestToJSONTyped(
  value?: LogoutUserRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    refreshToken: value['refreshToken'],
  };
}
