/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    type: NotificationTypeEnum;
    /**
     * ID de l'utilisateur ayant initié l'action
     * @type {string}
     * @memberof Notification
     */
    initiatorId: string;
    /**
     * 
     * @type {User}
     * @memberof Notification
     */
    initiator?: User;
    /**
     * ID de la page ou de l'élément concerné
     * @type {string}
     * @memberof Notification
     */
    targetId: string;
    /**
     * Message de la notification
     * @type {string}
     * @memberof Notification
     */
    message: string;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    createdAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Notification
     */
    read: boolean;
}


/**
 * @export
 */
export const NotificationTypeEnum = {
    Like: 'like',
    Comment: 'comment',
    Follow: 'follow',
    Repost: 'repost',
    Quote: 'quote',
    Mention: 'mention'
} as const;
export type NotificationTypeEnum = typeof NotificationTypeEnum[keyof typeof NotificationTypeEnum];


/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('initiatorId' in value) || value['initiatorId'] === undefined) return false;
    if (!('targetId' in value) || value['targetId'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('read' in value) || value['read'] === undefined) return false;
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'type': json['type'],
        'initiatorId': json['initiatorId'],
        'initiator': json['initiator'] == null ? undefined : UserFromJSON(json['initiator']),
        'targetId': json['targetId'],
        'message': json['message'],
        'createdAt': (new Date(json['createdAt'])),
        'read': json['read'],
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'type': value['type'],
        'initiatorId': value['initiatorId'],
        'initiator': UserToJSON(value['initiator']),
        'targetId': value['targetId'],
        'message': value['message'],
        'createdAt': ((value['createdAt']).toISOString()),
        'read': value['read'],
    };
}

