/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Offer
 */
export interface Offer {
  /**
   *
   * @type {string}
   * @memberof Offer
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Offer
   */
  name: OfferNameEnum;
  /**
   *
   * @type {number}
   * @memberof Offer
   */
  price: number;
  /**
   *
   * @type {string}
   * @memberof Offer
   */
  currency: string;
  /**
   *
   * @type {string}
   * @memberof Offer
   */
  description?: string;
}

/**
 * @export
 */
export const OfferNameEnum = {
  Basic: 'BASIC',
  Silver: 'SILVER',
  Premium: 'PREMIUM',
} as const;
export type OfferNameEnum = (typeof OfferNameEnum)[keyof typeof OfferNameEnum];

/**
 * Check if a given object implements the Offer interface.
 */
export function instanceOfOffer(value: object): value is Offer {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('price' in value) || value['price'] === undefined) return false;
  if (!('currency' in value) || value['currency'] === undefined) return false;
  return true;
}

export function OfferFromJSON(json: any): Offer {
  return OfferFromJSONTyped(json, false);
}

export function OfferFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Offer {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    price: json['price'],
    currency: json['currency'],
    description: json['description'] == null ? undefined : json['description'],
  };
}

export function OfferToJSON(json: any): Offer {
  return OfferToJSONTyped(json, false);
}

export function OfferToJSONTyped(
  value?: Offer | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    price: value['price'],
    currency: value['currency'],
    description: value['description'],
  };
}
