/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Offer
 */
export interface Offer {
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    name: OfferNameEnum;
    /**
     * 
     * @type {number}
     * @memberof Offer
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof Offer
     */
    description: string;
    /**
     * Nombre maximum de posts par jour
     * @type {number}
     * @memberof Offer
     */
    maxPosts: number;
    /**
     * Nombre maximum de likes par jour
     * @type {number}
     * @memberof Offer
     */
    maxLikes: number;
    /**
     * Accès aux fonctionnalités premium
     * @type {boolean}
     * @memberof Offer
     */
    premiumAccess: boolean;
    /**
     * Accès au Hall of Fame
     * @type {boolean}
     * @memberof Offer
     */
    hallOfFameAccess: boolean;
    /**
     * Bonus de points pour l'éligibilité au Hall of Fame (0 pour free, 4 pour basic, 6 pour premium)
     * @type {number}
     * @memberof Offer
     */
    hallOfFameBonus: number;
}


/**
 * @export
 */
export const OfferNameEnum = {
    Free: 'free',
    Basic: 'basic',
    Premium: 'premium'
} as const;
export type OfferNameEnum = typeof OfferNameEnum[keyof typeof OfferNameEnum];


/**
 * Check if a given object implements the Offer interface.
 */
export function instanceOfOffer(value: object): value is Offer {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('maxPosts' in value) || value['maxPosts'] === undefined) return false;
    if (!('maxLikes' in value) || value['maxLikes'] === undefined) return false;
    if (!('premiumAccess' in value) || value['premiumAccess'] === undefined) return false;
    if (!('hallOfFameAccess' in value) || value['hallOfFameAccess'] === undefined) return false;
    if (!('hallOfFameBonus' in value) || value['hallOfFameBonus'] === undefined) return false;
    return true;
}

export function OfferFromJSON(json: any): Offer {
    return OfferFromJSONTyped(json, false);
}

export function OfferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Offer {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'price': json['price'],
        'description': json['description'],
        'maxPosts': json['maxPosts'],
        'maxLikes': json['maxLikes'],
        'premiumAccess': json['premiumAccess'],
        'hallOfFameAccess': json['hallOfFameAccess'],
        'hallOfFameBonus': json['hallOfFameBonus'],
    };
}

export function OfferToJSON(json: any): Offer {
    return OfferToJSONTyped(json, false);
}

export function OfferToJSONTyped(value?: Offer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'price': value['price'],
        'description': value['description'],
        'maxPosts': value['maxPosts'],
        'maxLikes': value['maxLikes'],
        'premiumAccess': value['premiumAccess'],
        'hallOfFameAccess': value['hallOfFameAccess'],
        'hallOfFameBonus': value['hallOfFameBonus'],
    };
}

