/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Opportunity
 */
export interface Opportunity {
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    type: OpportunityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    url: string;
}


/**
 * @export
 */
export const OpportunityTypeEnum = {
    Job: 'job',
    Freelance: 'freelance',
    Event: 'event',
    SupportGroup: 'support_group'
} as const;
export type OpportunityTypeEnum = typeof OpportunityTypeEnum[keyof typeof OpportunityTypeEnum];


/**
 * Check if a given object implements the Opportunity interface.
 */
export function instanceOfOpportunity(value: object): value is Opportunity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function OpportunityFromJSON(json: any): Opportunity {
    return OpportunityFromJSONTyped(json, false);
}

export function OpportunityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Opportunity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'title': json['title'],
        'description': json['description'],
        'url': json['url'],
    };
}

export function OpportunityToJSON(json: any): Opportunity {
    return OpportunityToJSONTyped(json, false);
}

export function OpportunityToJSONTyped(value?: Opportunity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'title': value['title'],
        'description': value['description'],
        'url': value['url'],
    };
}

