/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Opportunity
 */
export interface Opportunity {
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    type?: OpportunityTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Opportunity
     */
    description?: string;
}


/**
 * @export
 */
export const OpportunityTypeEnum = {
    Job: 'job',
    Freelance: 'freelance',
    Event: 'event',
    SupportGroup: 'support_group'
} as const;
export type OpportunityTypeEnum = typeof OpportunityTypeEnum[keyof typeof OpportunityTypeEnum];


/**
 * Check if a given object implements the Opportunity interface.
 */
export function instanceOfOpportunity(value: object): value is Opportunity {
    return true;
}

export function OpportunityFromJSON(json: any): Opportunity {
    return OpportunityFromJSONTyped(json, false);
}

export function OpportunityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Opportunity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
        'url': json['url'] == null ? undefined : json['url'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function OpportunityToJSON(json: any): Opportunity {
    return OpportunityToJSONTyped(json, false);
}

export function OpportunityToJSONTyped(value?: Opportunity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'type': value['type'],
        'url': value['url'],
        'description': value['description'],
    };
}

