/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuotePageRequest
 */
export interface QuotePageRequest {
    /**
     * Contenu du nouveau post qui cite la page
     * @type {string}
     * @memberof QuotePageRequest
     */
    content: string;
}

/**
 * Check if a given object implements the QuotePageRequest interface.
 */
export function instanceOfQuotePageRequest(value: object): value is QuotePageRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function QuotePageRequestFromJSON(json: any): QuotePageRequest {
    return QuotePageRequestFromJSONTyped(json, false);
}

export function QuotePageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotePageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
    };
}

export function QuotePageRequestToJSON(json: any): QuotePageRequest {
    return QuotePageRequestToJSONTyped(json, false);
}

export function QuotePageRequestToJSONTyped(value?: QuotePageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
    };
}

