/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReactionInput
 */
export interface ReactionInput {
  /**
   *
   * @type {string}
   * @memberof ReactionInput
   */
  emoji: string;
}

/**
 * Check if a given object implements the ReactionInput interface.
 */
export function instanceOfReactionInput(value: object): value is ReactionInput {
  if (!('emoji' in value) || value['emoji'] === undefined) return false;
  return true;
}

export function ReactionInputFromJSON(json: any): ReactionInput {
  return ReactionInputFromJSONTyped(json, false);
}

export function ReactionInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ReactionInput {
  if (json == null) {
    return json;
  }
  return {
    emoji: json['emoji'],
  };
}

export function ReactionInputToJSON(json: any): ReactionInput {
  return ReactionInputToJSONTyped(json, false);
}

export function ReactionInputToJSONTyped(
  value?: ReactionInput | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    emoji: value['emoji'],
  };
}
