/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RepostPage200Response
 */
export interface RepostPage200Response {
    /**
     * 
     * @type {number}
     * @memberof RepostPage200Response
     */
    reposts?: number;
}

/**
 * Check if a given object implements the RepostPage200Response interface.
 */
export function instanceOfRepostPage200Response(value: object): value is RepostPage200Response {
    return true;
}

export function RepostPage200ResponseFromJSON(json: any): RepostPage200Response {
    return RepostPage200ResponseFromJSONTyped(json, false);
}

export function RepostPage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepostPage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'reposts': json['reposts'] == null ? undefined : json['reposts'],
    };
}

export function RepostPage200ResponseToJSON(json: any): RepostPage200Response {
    return RepostPage200ResponseToJSONTyped(json, false);
}

export function RepostPage200ResponseToJSONTyped(value?: RepostPage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reposts': value['reposts'],
    };
}

