/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EndPage } from './EndPage';
import {
    EndPageFromJSON,
    EndPageFromJSONTyped,
    EndPageToJSON,
    EndPageToJSONTyped,
} from './EndPage';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { ListTrendingHashtags200ResponseInner } from './ListTrendingHashtags200ResponseInner';
import {
    ListTrendingHashtags200ResponseInnerFromJSON,
    ListTrendingHashtags200ResponseInnerFromJSONTyped,
    ListTrendingHashtags200ResponseInnerToJSON,
    ListTrendingHashtags200ResponseInnerToJSONTyped,
} from './ListTrendingHashtags200ResponseInner';

/**
 * 
 * @export
 * @interface SearchContent200Response
 */
export interface SearchContent200Response {
    /**
     * 
     * @type {Array<EndPage>}
     * @memberof SearchContent200Response
     */
    posts?: Array<EndPage>;
    /**
     * 
     * @type {Array<User>}
     * @memberof SearchContent200Response
     */
    users?: Array<User>;
    /**
     * 
     * @type {Array<ListTrendingHashtags200ResponseInner>}
     * @memberof SearchContent200Response
     */
    hashtags?: Array<ListTrendingHashtags200ResponseInner>;
}

/**
 * Check if a given object implements the SearchContent200Response interface.
 */
export function instanceOfSearchContent200Response(value: object): value is SearchContent200Response {
    return true;
}

export function SearchContent200ResponseFromJSON(json: any): SearchContent200Response {
    return SearchContent200ResponseFromJSONTyped(json, false);
}

export function SearchContent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchContent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(EndPageFromJSON)),
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserFromJSON)),
        'hashtags': json['hashtags'] == null ? undefined : ((json['hashtags'] as Array<any>).map(ListTrendingHashtags200ResponseInnerFromJSON)),
    };
}

export function SearchContent200ResponseToJSON(json: any): SearchContent200Response {
    return SearchContent200ResponseToJSONTyped(json, false);
}

export function SearchContent200ResponseToJSONTyped(value?: SearchContent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(EndPageToJSON)),
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserToJSON)),
        'hashtags': value['hashtags'] == null ? undefined : ((value['hashtags'] as Array<any>).map(ListTrendingHashtags200ResponseInnerToJSON)),
    };
}

