/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called -->
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendContactFormRequest
 */
export interface SendContactFormRequest {
    /**
     * 
     * @type {string}
     * @memberof SendContactFormRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SendContactFormRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof SendContactFormRequest
     */
    message: string;
}

/**
 * Check if a given object implements the SendContactFormRequest interface.
 */
export function instanceOfSendContactFormRequest(value: object): value is SendContactFormRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SendContactFormRequestFromJSON(json: any): SendContactFormRequest {
    return SendContactFormRequestFromJSONTyped(json, false);
}

export function SendContactFormRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendContactFormRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
        'message': json['message'],
    };
}

export function SendContactFormRequestToJSON(json: any): SendContactFormRequest {
    return SendContactFormRequestToJSONTyped(json, false);
}

export function SendContactFormRequestToJSONTyped(value?: SendContactFormRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'message': value['message'],
    };
}

