/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Offer } from './Offer';
import {
    OfferFromJSON,
    OfferFromJSONTyped,
    OfferToJSON,
    OfferToJSONTyped,
} from './Offer';

/**
 * 
 * @export
 * @interface SubscriptionResponse
 */
export interface SubscriptionResponse {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponse
     */
    subscriptionId: string;
    /**
     * 
     * @type {Offer}
     * @memberof SubscriptionResponse
     */
    offer: Offer;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponse
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponse
     */
    expiryDate: Date;
}

/**
 * Check if a given object implements the SubscriptionResponse interface.
 */
export function instanceOfSubscriptionResponse(value: object): value is SubscriptionResponse {
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    if (!('offer' in value) || value['offer'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    return true;
}

export function SubscriptionResponseFromJSON(json: any): SubscriptionResponse {
    return SubscriptionResponseFromJSONTyped(json, false);
}

export function SubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionId': json['subscriptionId'],
        'offer': OfferFromJSON(json['offer']),
        'startDate': (new Date(json['startDate'])),
        'expiryDate': (new Date(json['expiryDate'])),
    };
}

export function SubscriptionResponseToJSON(json: any): SubscriptionResponse {
    return SubscriptionResponseToJSONTyped(json, false);
}

export function SubscriptionResponseToJSONTyped(value?: SubscriptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriptionId': value['subscriptionId'],
        'offer': OfferToJSON(value['offer']),
        'startDate': ((value['startDate']).toISOString()),
        'expiryDate': ((value['expiryDate']).toISOString()),
    };
}

