/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscribeToOfferRequestCardDetails } from './SubscribeToOfferRequestCardDetails';
import {
  SubscribeToOfferRequestCardDetailsFromJSON,
  SubscribeToOfferRequestCardDetailsFromJSONTyped,
  SubscribeToOfferRequestCardDetailsToJSON,
  SubscribeToOfferRequestCardDetailsToJSONTyped,
} from './SubscribeToOfferRequestCardDetails';
import type { SubscribeToOfferRequestMobilePayment } from './SubscribeToOfferRequestMobilePayment';
import {
  SubscribeToOfferRequestMobilePaymentFromJSON,
  SubscribeToOfferRequestMobilePaymentFromJSONTyped,
  SubscribeToOfferRequestMobilePaymentToJSON,
  SubscribeToOfferRequestMobilePaymentToJSONTyped,
} from './SubscribeToOfferRequestMobilePayment';

/**
 *
 * @export
 * @interface SubscribeToOfferRequest
 */
export interface SubscribeToOfferRequest {
  /**
   *
   * @type {string}
   * @memberof SubscribeToOfferRequest
   */
  offerId: string;
  /**
   *
   * @type {string}
   * @memberof SubscribeToOfferRequest
   */
  paymentMethod: SubscribeToOfferRequestPaymentMethodEnum;
  /**
   *
   * @type {number}
   * @memberof SubscribeToOfferRequest
   */
  amount: number;
  /**
   *
   * @type {SubscribeToOfferRequestCardDetails}
   * @memberof SubscribeToOfferRequest
   */
  cardDetails?: SubscribeToOfferRequestCardDetails;
  /**
   *
   * @type {SubscribeToOfferRequestMobilePayment}
   * @memberof SubscribeToOfferRequest
   */
  mobilePayment?: SubscribeToOfferRequestMobilePayment;
}

/**
 * @export
 */
export const SubscribeToOfferRequestPaymentMethodEnum = {
  Card: 'card',
  Mvola: 'mvola',
} as const;
export type SubscribeToOfferRequestPaymentMethodEnum =
  (typeof SubscribeToOfferRequestPaymentMethodEnum)[keyof typeof SubscribeToOfferRequestPaymentMethodEnum];

/**
 * Check if a given object implements the SubscribeToOfferRequest interface.
 */
export function instanceOfSubscribeToOfferRequest(
  value: object
): value is SubscribeToOfferRequest {
  if (!('offerId' in value) || value['offerId'] === undefined) return false;
  if (!('paymentMethod' in value) || value['paymentMethod'] === undefined)
    return false;
  if (!('amount' in value) || value['amount'] === undefined) return false;
  return true;
}

export function SubscribeToOfferRequestFromJSON(
  json: any
): SubscribeToOfferRequest {
  return SubscribeToOfferRequestFromJSONTyped(json, false);
}

export function SubscribeToOfferRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscribeToOfferRequest {
  if (json == null) {
    return json;
  }
  return {
    offerId: json['offerId'],
    paymentMethod: json['paymentMethod'],
    amount: json['amount'],
    cardDetails:
      json['cardDetails'] == null
        ? undefined
        : SubscribeToOfferRequestCardDetailsFromJSON(json['cardDetails']),
    mobilePayment:
      json['mobilePayment'] == null
        ? undefined
        : SubscribeToOfferRequestMobilePaymentFromJSON(json['mobilePayment']),
  };
}

export function SubscribeToOfferRequestToJSON(
  json: any
): SubscribeToOfferRequest {
  return SubscribeToOfferRequestToJSONTyped(json, false);
}

export function SubscribeToOfferRequestToJSONTyped(
  value?: SubscribeToOfferRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    offerId: value['offerId'],
    paymentMethod: value['paymentMethod'],
    amount: value['amount'],
    cardDetails: SubscribeToOfferRequestCardDetailsToJSON(value['cardDetails']),
    mobilePayment: SubscribeToOfferRequestMobilePaymentToJSON(
      value['mobilePayment']
    ),
  };
}
