/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscribeToOfferRequestCardDetails
 */
export interface SubscribeToOfferRequestCardDetails {
    /**
     * 
     * @type {string}
     * @memberof SubscribeToOfferRequestCardDetails
     */
    nameOnCard: string;
    /**
     * 
     * @type {string}
     * @memberof SubscribeToOfferRequestCardDetails
     */
    cardNumber: string;
    /**
     * 
     * @type {string}
     * @memberof SubscribeToOfferRequestCardDetails
     */
    expiryDate: string;
    /**
     * 
     * @type {string}
     * @memberof SubscribeToOfferRequestCardDetails
     */
    cvc: string;
}

/**
 * Check if a given object implements the SubscribeToOfferRequestCardDetails interface.
 */
export function instanceOfSubscribeToOfferRequestCardDetails(value: object): value is SubscribeToOfferRequestCardDetails {
    if (!('nameOnCard' in value) || value['nameOnCard'] === undefined) return false;
    if (!('cardNumber' in value) || value['cardNumber'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('cvc' in value) || value['cvc'] === undefined) return false;
    return true;
}

export function SubscribeToOfferRequestCardDetailsFromJSON(json: any): SubscribeToOfferRequestCardDetails {
    return SubscribeToOfferRequestCardDetailsFromJSONTyped(json, false);
}

export function SubscribeToOfferRequestCardDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscribeToOfferRequestCardDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'nameOnCard': json['nameOnCard'],
        'cardNumber': json['cardNumber'],
        'expiryDate': json['expiryDate'],
        'cvc': json['cvc'],
    };
}

export function SubscribeToOfferRequestCardDetailsToJSON(json: any): SubscribeToOfferRequestCardDetails {
    return SubscribeToOfferRequestCardDetailsToJSONTyped(json, false);
}

export function SubscribeToOfferRequestCardDetailsToJSONTyped(value?: SubscribeToOfferRequestCardDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nameOnCard': value['nameOnCard'],
        'cardNumber': value['cardNumber'],
        'expiryDate': value['expiryDate'],
        'cvc': value['cvc'],
    };
}

