/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscribeToOfferRequest
 */
export interface SubscribeToOfferRequest {
    /**
     * 
     * @type {string}
     * @memberof SubscribeToOfferRequest
     */
    offerId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscribeToOfferRequest
     */
    paymentMethod: SubscribeToOfferRequestPaymentMethodEnum;
}


/**
 * @export
 */
export const SubscribeToOfferRequestPaymentMethodEnum = {
    Card: 'card',
    Paypal: 'paypal',
    BankTransfer: 'bank_transfer'
} as const;
export type SubscribeToOfferRequestPaymentMethodEnum = typeof SubscribeToOfferRequestPaymentMethodEnum[keyof typeof SubscribeToOfferRequestPaymentMethodEnum];


/**
 * Check if a given object implements the SubscribeToOfferRequest interface.
 */
export function instanceOfSubscribeToOfferRequest(value: object): value is SubscribeToOfferRequest {
    if (!('offerId' in value) || value['offerId'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function SubscribeToOfferRequestFromJSON(json: any): SubscribeToOfferRequest {
    return SubscribeToOfferRequestFromJSONTyped(json, false);
}

export function SubscribeToOfferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscribeToOfferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'offerId': json['offerId'],
        'paymentMethod': json['paymentMethod'],
    };
}

export function SubscribeToOfferRequestToJSON(json: any): SubscribeToOfferRequest {
    return SubscribeToOfferRequestToJSONTyped(json, false);
}

export function SubscribeToOfferRequestToJSONTyped(value?: SubscribeToOfferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offerId': value['offerId'],
        'paymentMethod': value['paymentMethod'],
    };
}

