/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubscribeToOffer200Response
 */
export interface SubscribeToOffer200Response {
  /**
   *
   * @type {string}
   * @memberof SubscribeToOffer200Response
   */
  status?: string;
  /**
   *
   * @type {string}
   * @memberof SubscribeToOffer200Response
   */
  transactionId?: string;
}

/**
 * Check if a given object implements the SubscribeToOffer200Response interface.
 */
export function instanceOfSubscribeToOffer200Response(
  value: object
): value is SubscribeToOffer200Response {
  return true;
}

export function SubscribeToOffer200ResponseFromJSON(
  json: any
): SubscribeToOffer200Response {
  return SubscribeToOffer200ResponseFromJSONTyped(json, false);
}

export function SubscribeToOffer200ResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscribeToOffer200Response {
  if (json == null) {
    return json;
  }
  return {
    status: json['status'] == null ? undefined : json['status'],
    transactionId:
      json['transactionId'] == null ? undefined : json['transactionId'],
  };
}

export function SubscribeToOffer200ResponseToJSON(
  json: any
): SubscribeToOffer200Response {
  return SubscribeToOffer200ResponseToJSONTyped(json, false);
}

export function SubscribeToOffer200ResponseToJSONTyped(
  value?: SubscribeToOffer200Response | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    status: value['status'],
    transactionId: value['transactionId'],
  };
}
