/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    offerId: string;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    expiryDate: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Subscription
     */
    active: boolean;
}

/**
 * Check if a given object implements the Subscription interface.
 */
export function instanceOfSubscription(value: object): value is Subscription {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('offerId' in value) || value['offerId'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('expiryDate' in value) || value['expiryDate'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    return true;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'offerId': json['offerId'],
        'startDate': (new Date(json['startDate'])),
        'expiryDate': (new Date(json['expiryDate'])),
        'active': json['active'],
    };
}

export function SubscriptionToJSON(json: any): Subscription {
    return SubscriptionToJSONTyped(json, false);
}

export function SubscriptionToJSONTyped(value?: Subscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'offerId': value['offerId'],
        'startDate': ((value['startDate']).toISOString()),
        'expiryDate': ((value['expiryDate']).toISOString()),
        'active': value['active'],
    };
}

