/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubscribeToOfferRequestMobilePayment
 */
export interface SubscribeToOfferRequestMobilePayment {
  /**
   *
   * @type {string}
   * @memberof SubscribeToOfferRequestMobilePayment
   */
  phoneNumber: string;
}

/**
 * Check if a given object implements the SubscribeToOfferRequestMobilePayment interface.
 */
export function instanceOfSubscribeToOfferRequestMobilePayment(
  value: object
): value is SubscribeToOfferRequestMobilePayment {
  if (!('phoneNumber' in value) || value['phoneNumber'] === undefined)
    return false;
  return true;
}

export function SubscribeToOfferRequestMobilePaymentFromJSON(
  json: any
): SubscribeToOfferRequestMobilePayment {
  return SubscribeToOfferRequestMobilePaymentFromJSONTyped(json, false);
}

export function SubscribeToOfferRequestMobilePaymentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscribeToOfferRequestMobilePayment {
  if (json == null) {
    return json;
  }
  return {
    phoneNumber: json['phoneNumber'],
  };
}

export function SubscribeToOfferRequestMobilePaymentToJSON(
  json: any
): SubscribeToOfferRequestMobilePayment {
  return SubscribeToOfferRequestMobilePaymentToJSONTyped(json, false);
}

export function SubscribeToOfferRequestMobilePaymentToJSONTyped(
  value?: SubscribeToOfferRequestMobilePayment | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    phoneNumber: value['phoneNumber'],
  };
}
