/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleLikePageRequest
 */
export interface ToggleLikePageRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ToggleLikePageRequest
     */
    like: boolean;
}

/**
 * Check if a given object implements the ToggleLikePageRequest interface.
 */
export function instanceOfToggleLikePageRequest(value: object): value is ToggleLikePageRequest {
    if (!('like' in value) || value['like'] === undefined) return false;
    return true;
}

export function ToggleLikePageRequestFromJSON(json: any): ToggleLikePageRequest {
    return ToggleLikePageRequestFromJSONTyped(json, false);
}

export function ToggleLikePageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleLikePageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'like': json['like'],
    };
}

export function ToggleLikePageRequestToJSON(json: any): ToggleLikePageRequest {
    return ToggleLikePageRequestToJSONTyped(json, false);
}

export function ToggleLikePageRequestToJSONTyped(value?: ToggleLikePageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'like': value['like'],
    };
}

