/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleSavePageRequest
 */
export interface ToggleSavePageRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ToggleSavePageRequest
     */
    save: boolean;
}

/**
 * Check if a given object implements the ToggleSavePageRequest interface.
 */
export function instanceOfToggleSavePageRequest(value: object): value is ToggleSavePageRequest {
    if (!('save' in value) || value['save'] === undefined) return false;
    return true;
}

export function ToggleSavePageRequestFromJSON(json: any): ToggleSavePageRequest {
    return ToggleSavePageRequestFromJSONTyped(json, false);
}

export function ToggleSavePageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleSavePageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'save': json['save'],
    };
}

export function ToggleSavePageRequestToJSON(json: any): ToggleSavePageRequest {
    return ToggleSavePageRequestToJSONTyped(json, false);
}

export function ToggleSavePageRequestToJSONTyped(value?: ToggleSavePageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'save': value['save'],
    };
}

