/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleSavePage200Response
 */
export interface ToggleSavePage200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ToggleSavePage200Response
     */
    saved?: boolean;
}

/**
 * Check if a given object implements the ToggleSavePage200Response interface.
 */
export function instanceOfToggleSavePage200Response(value: object): value is ToggleSavePage200Response {
    return true;
}

export function ToggleSavePage200ResponseFromJSON(json: any): ToggleSavePage200Response {
    return ToggleSavePage200ResponseFromJSONTyped(json, false);
}

export function ToggleSavePage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleSavePage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'saved': json['saved'] == null ? undefined : json['saved'],
    };
}

export function ToggleSavePage200ResponseToJSON(json: any): ToggleSavePage200Response {
    return ToggleSavePage200ResponseToJSONTyped(json, false);
}

export function ToggleSavePage200ResponseToJSONTyped(value?: ToggleSavePage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'saved': value['saved'],
    };
}

