/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleFollowUserRequest
 */
export interface ToggleFollowUserRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ToggleFollowUserRequest
     */
    follow: boolean;
}

/**
 * Check if a given object implements the ToggleFollowUserRequest interface.
 */
export function instanceOfToggleFollowUserRequest(value: object): value is ToggleFollowUserRequest {
    if (!('follow' in value) || value['follow'] === undefined) return false;
    return true;
}

export function ToggleFollowUserRequestFromJSON(json: any): ToggleFollowUserRequest {
    return ToggleFollowUserRequestFromJSONTyped(json, false);
}

export function ToggleFollowUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleFollowUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'follow': json['follow'],
    };
}

export function ToggleFollowUserRequestToJSON(json: any): ToggleFollowUserRequest {
    return ToggleFollowUserRequestToJSONTyped(json, false);
}

export function ToggleFollowUserRequestToJSONTyped(value?: ToggleFollowUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'follow': value['follow'],
    };
}

