/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleLikePage200Response
 */
export interface ToggleLikePage200Response {
    /**
     * 
     * @type {number}
     * @memberof ToggleLikePage200Response
     */
    likes?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ToggleLikePage200Response
     */
    liked?: boolean;
}

/**
 * Check if a given object implements the ToggleLikePage200Response interface.
 */
export function instanceOfToggleLikePage200Response(value: object): value is ToggleLikePage200Response {
    return true;
}

export function ToggleLikePage200ResponseFromJSON(json: any): ToggleLikePage200Response {
    return ToggleLikePage200ResponseFromJSONTyped(json, false);
}

export function ToggleLikePage200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleLikePage200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'likes': json['likes'] == null ? undefined : json['likes'],
        'liked': json['liked'] == null ? undefined : json['liked'],
    };
}

export function ToggleLikePage200ResponseToJSON(json: any): ToggleLikePage200Response {
    return ToggleLikePage200ResponseToJSONTyped(json, false);
}

export function ToggleLikePage200ResponseToJSONTyped(value?: ToggleLikePage200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'likes': value['likes'],
        'liked': value['liked'],
    };
}

