/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleHallOfFamePageRequest
 */
export interface ToggleHallOfFamePageRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ToggleHallOfFamePageRequest
     */
    inHallOfFame: boolean;
}

/**
 * Check if a given object implements the ToggleHallOfFamePageRequest interface.
 */
export function instanceOfToggleHallOfFamePageRequest(value: object): value is ToggleHallOfFamePageRequest {
    if (!('inHallOfFame' in value) || value['inHallOfFame'] === undefined) return false;
    return true;
}

export function ToggleHallOfFamePageRequestFromJSON(json: any): ToggleHallOfFamePageRequest {
    return ToggleHallOfFamePageRequestFromJSONTyped(json, false);
}

export function ToggleHallOfFamePageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleHallOfFamePageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'inHallOfFame': json['inHallOfFame'],
    };
}

export function ToggleHallOfFamePageRequestToJSON(json: any): ToggleHallOfFamePageRequest {
    return ToggleHallOfFamePageRequestToJSONTyped(json, false);
}

export function ToggleHallOfFamePageRequestToJSONTyped(value?: ToggleHallOfFamePageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'inHallOfFame': value['inHallOfFame'],
    };
}

