/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EndPage } from './EndPage';
import {
    EndPageFromJSON,
    EndPageFromJSONTyped,
    EndPageToJSON,
    EndPageToJSONTyped,
} from './EndPage';
import type { Follow } from './Follow';
import {
    FollowFromJSON,
    FollowFromJSONTyped,
    FollowToJSON,
    FollowToJSONTyped,
} from './Follow';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
    SubscriptionToJSONTyped,
} from './Subscription';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    role: UserRoleEnum;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;
    /**
     * URL de l'image de profil de l'utilisateur
     * @type {string}
     * @memberof User
     */
    avatar?: string | null;
    /**
     * Nom d'utilisateur
     * @type {string}
     * @memberof User
     */
    name?: string | null;
    /**
     * Biographie de l'utilisateur
     * @type {string}
     * @memberof User
     */
    bio?: string | null;
    /**
     * Liste des utilisateurs qui suivent cet utilisateur
     * @type {Array<Follow>}
     * @memberof User
     */
    followers?: Array<Follow>;
    /**
     * Liste des utilisateurs suivis par cet utilisateur
     * @type {Array<Follow>}
     * @memberof User
     */
    following?: Array<Follow>;
    /**
     * Liste des posts de l'utilisateur
     * @type {Array<EndPage>}
     * @memberof User
     */
    posts?: Array<EndPage>;
    /**
     * 
     * @type {Subscription}
     * @memberof User
     */
    subscription?: Subscription;
}


/**
 * @export
 */
export const UserRoleEnum = {
    User: 'user',
    Admin: 'admin'
} as const;
export type UserRoleEnum = typeof UserRoleEnum[keyof typeof UserRoleEnum];


/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'email': json['email'],
        'role': json['role'],
        'createdAt': (new Date(json['createdAt'])),
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'name': json['name'] == null ? undefined : json['name'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'followers': json['followers'] == null ? undefined : ((json['followers'] as Array<any>).map(FollowFromJSON)),
        'following': json['following'] == null ? undefined : ((json['following'] as Array<any>).map(FollowFromJSON)),
        'posts': json['posts'] == null ? undefined : ((json['posts'] as Array<any>).map(EndPageFromJSON)),
        'subscription': json['subscription'] == null ? undefined : SubscriptionFromJSON(json['subscription']),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'role': value['role'],
        'createdAt': ((value['createdAt']).toISOString()),
        'avatar': value['avatar'],
        'name': value['name'],
        'bio': value['bio'],
        'followers': value['followers'] == null ? undefined : ((value['followers'] as Array<any>).map(FollowToJSON)),
        'following': value['following'] == null ? undefined : ((value['following'] as Array<any>).map(FollowToJSON)),
        'posts': value['posts'] == null ? undefined : ((value['posts'] as Array<any>).map(EndPageToJSON)),
        'subscription': SubscriptionToJSON(value['subscription']),
    };
}

