/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdateInput
 */
export interface UserUpdateInput {
    /**
     * 
     * @type {string}
     * @memberof UserUpdateInput
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateInput
     */
    bio?: string | null;
    /**
     * URL de l'image de profil de l'utilisateur
     * @type {string}
     * @memberof UserUpdateInput
     */
    avatar?: string | null;
}

/**
 * Check if a given object implements the UserUpdateInput interface.
 */
export function instanceOfUserUpdateInput(value: object): value is UserUpdateInput {
    return true;
}

export function UserUpdateInputFromJSON(json: any): UserUpdateInput {
    return UserUpdateInputFromJSONTyped(json, false);
}

export function UserUpdateInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'bio': json['bio'] == null ? undefined : json['bio'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
    };
}

export function UserUpdateInputToJSON(json: any): UserUpdateInput {
    return UserUpdateInputToJSONTyped(json, false);
}

export function UserUpdateInputToJSONTyped(value?: UserUpdateInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'bio': value['bio'],
        'avatar': value['avatar'],
    };
}

