/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EndPage,
  EndPageInput,
} from '../models/index';
import {
    EndPageFromJSON,
    EndPageToJSON,
    EndPageInputFromJSON,
    EndPageInputToJSON,
} from '../models/index';

export interface CreateEndPageRequest {
    endPageInput: EndPageInput;
}

export interface DeleteEndPageRequest {
    id: string;
}

export interface GetEndPageRequest {
    id: string;
}

export interface ListEndPagesRequest {
    tone?: ListEndPagesToneEnum;
    userId?: string;
}

/**
 * 
 */
export class EndPagesApi extends runtime.BaseAPI {

    /**
     * Créer une nouvelle page de fin
     */
    async createEndPageRaw(requestParameters: CreateEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EndPage>> {
        if (requestParameters['endPageInput'] == null) {
            throw new runtime.RequiredError(
                'endPageInput',
                'Required parameter "endPageInput" was null or undefined when calling createEndPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EndPageInputToJSON(requestParameters['endPageInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EndPageFromJSON(jsonValue));
    }

    /**
     * Créer une nouvelle page de fin
     */
    async createEndPage(requestParameters: CreateEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EndPage> {
        const response = await this.createEndPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Supprimer une page de fin
     */
    async deleteEndPageRaw(requestParameters: DeleteEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEndPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Supprimer une page de fin
     */
    async deleteEndPage(requestParameters: DeleteEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEndPageRaw(requestParameters, initOverrides);
    }

    /**
     * Consulter une page de fin spécifique
     */
    async getEndPageRaw(requestParameters: GetEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EndPage>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEndPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/end-pages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EndPageFromJSON(jsonValue));
    }

    /**
     * Consulter une page de fin spécifique
     */
    async getEndPage(requestParameters: GetEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EndPage> {
        const response = await this.getEndPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lister les pages publiques
     */
    async listEndPagesRaw(requestParameters: ListEndPagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EndPage>>> {
        const queryParameters: any = {};

        if (requestParameters['tone'] != null) {
            queryParameters['tone'] = requestParameters['tone'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/end-pages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EndPageFromJSON));
    }

    /**
     * Lister les pages publiques
     */
    async listEndPages(requestParameters: ListEndPagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EndPage>> {
        const response = await this.listEndPagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListEndPagesToneEnum = {
    Dramatic: 'dramatic',
    Ironic: 'ironic',
    Cringe: 'cringe',
    Classy: 'classy',
    Touching: 'touching',
    Absurd: 'absurd',
    PassiveAggressive: 'passive_aggressive',
    Honest: 'honest'
} as const;
export type ListEndPagesToneEnum = typeof ListEndPagesToneEnum[keyof typeof ListEndPagesToneEnum];
