/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EndPage,
  EndPageInput,
  QuotePageRequest,
  RepostPage200Response,
  ToggleLikePage200Response,
  ToggleLikePageRequest,
  ToggleSavePage200Response,
  ToggleSavePageRequest,
} from '../models/index';
import {
    EndPageFromJSON,
    EndPageToJSON,
    EndPageInputFromJSON,
    EndPageInputToJSON,
    QuotePageRequestFromJSON,
    QuotePageRequestToJSON,
    RepostPage200ResponseFromJSON,
    RepostPage200ResponseToJSON,
    ToggleLikePage200ResponseFromJSON,
    ToggleLikePage200ResponseToJSON,
    ToggleLikePageRequestFromJSON,
    ToggleLikePageRequestToJSON,
    ToggleSavePage200ResponseFromJSON,
    ToggleSavePage200ResponseToJSON,
    ToggleSavePageRequestFromJSON,
    ToggleSavePageRequestToJSON,
} from '../models/index';

export interface CreateEndPageRequest {
    endPageInput: EndPageInput;
}

export interface DeleteEndPageRequest {
    id: string;
}

export interface GetEndPageRequest {
    id: string;
}

export interface ListEndPagesRequest {
    tone?: ListEndPagesToneEnum;
    userId?: string;
}

export interface QuotePageOperationRequest {
    id: string;
    quotePageRequest: QuotePageRequest;
}

export interface RepostPageRequest {
    id: string;
}

export interface ToggleLikePageOperationRequest {
    id: string;
    toggleLikePageRequest: ToggleLikePageRequest;
}

export interface ToggleSavePageOperationRequest {
    id: string;
    toggleSavePageRequest: ToggleSavePageRequest;
}

/**
 * 
 */
export class EndPagesApi extends runtime.BaseAPI {

    /**
     * Créer une nouvelle page de fin
     */
    async createEndPageRaw(requestParameters: CreateEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EndPage>> {
        if (requestParameters['endPageInput'] == null) {
            throw new runtime.RequiredError(
                'endPageInput',
                'Required parameter "endPageInput" was null or undefined when calling createEndPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: EndPageInputToJSON(requestParameters['endPageInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EndPageFromJSON(jsonValue));
    }

    /**
     * Créer une nouvelle page de fin
     */
    async createEndPage(requestParameters: CreateEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EndPage> {
        const response = await this.createEndPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Supprimer une page de fin
     */
    async deleteEndPageRaw(requestParameters: DeleteEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEndPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Supprimer une page de fin
     */
    async deleteEndPage(requestParameters: DeleteEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteEndPageRaw(requestParameters, initOverrides);
    }

    /**
     * Consulter une page de fin spécifique
     */
    async getEndPageRaw(requestParameters: GetEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EndPage>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEndPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/end-pages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EndPageFromJSON(jsonValue));
    }

    /**
     * Consulter une page de fin spécifique
     */
    async getEndPage(requestParameters: GetEndPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EndPage> {
        const response = await this.getEndPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Récupérer le fil d\'actualité des utilisateurs suivis
     */
    async getTimelineRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EndPage>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages/timeline`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EndPageFromJSON));
    }

    /**
     * Récupérer le fil d\'actualité des utilisateurs suivis
     */
    async getTimeline(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EndPage>> {
        const response = await this.getTimelineRaw(initOverrides);
        return await response.value();
    }

    /**
     * Lister les pages publiques
     */
    async listEndPagesRaw(requestParameters: ListEndPagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EndPage>>> {
        const queryParameters: any = {};

        if (requestParameters['tone'] != null) {
            queryParameters['tone'] = requestParameters['tone'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/end-pages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EndPageFromJSON));
    }

    /**
     * Lister les pages publiques
     */
    async listEndPages(requestParameters: ListEndPagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EndPage>> {
        const response = await this.listEndPagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Lister les pages tendance
     */
    async listTrendingPagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EndPage>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/end-pages/trending`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EndPageFromJSON));
    }

    /**
     * Lister les pages tendance
     */
    async listTrendingPages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EndPage>> {
        const response = await this.listTrendingPagesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Citer une page dans un nouveau post
     */
    async quotePageRaw(requestParameters: QuotePageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EndPage>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling quotePage().'
            );
        }

        if (requestParameters['quotePageRequest'] == null) {
            throw new runtime.RequiredError(
                'quotePageRequest',
                'Required parameter "quotePageRequest" was null or undefined when calling quotePage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages/{id}/quote`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: QuotePageRequestToJSON(requestParameters['quotePageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EndPageFromJSON(jsonValue));
    }

    /**
     * Citer une page dans un nouveau post
     */
    async quotePage(requestParameters: QuotePageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EndPage> {
        const response = await this.quotePageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Reposter une page
     */
    async repostPageRaw(requestParameters: RepostPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RepostPage200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling repostPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages/{id}/repost`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RepostPage200ResponseFromJSON(jsonValue));
    }

    /**
     * Reposter une page
     */
    async repostPage(requestParameters: RepostPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RepostPage200Response> {
        const response = await this.repostPageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aimer ou retirer un like sur une page
     */
    async toggleLikePageRaw(requestParameters: ToggleLikePageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToggleLikePage200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toggleLikePage().'
            );
        }

        if (requestParameters['toggleLikePageRequest'] == null) {
            throw new runtime.RequiredError(
                'toggleLikePageRequest',
                'Required parameter "toggleLikePageRequest" was null or undefined when calling toggleLikePage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages/{id}/likes`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToggleLikePageRequestToJSON(requestParameters['toggleLikePageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToggleLikePage200ResponseFromJSON(jsonValue));
    }

    /**
     * Aimer ou retirer un like sur une page
     */
    async toggleLikePage(requestParameters: ToggleLikePageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToggleLikePage200Response> {
        const response = await this.toggleLikePageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sauvegarder ou retirer une page des favoris
     */
    async toggleSavePageRaw(requestParameters: ToggleSavePageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ToggleSavePage200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toggleSavePage().'
            );
        }

        if (requestParameters['toggleSavePageRequest'] == null) {
            throw new runtime.RequiredError(
                'toggleSavePageRequest',
                'Required parameter "toggleSavePageRequest" was null or undefined when calling toggleSavePage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages/{id}/save`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToggleSavePageRequestToJSON(requestParameters['toggleSavePageRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ToggleSavePage200ResponseFromJSON(jsonValue));
    }

    /**
     * Sauvegarder ou retirer une page des favoris
     */
    async toggleSavePage(requestParameters: ToggleSavePageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ToggleSavePage200Response> {
        const response = await this.toggleSavePageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListEndPagesToneEnum = {
    Dramatic: 'dramatic',
    Ironic: 'ironic',
    Cringe: 'cringe',
    Classy: 'classy',
    Touching: 'touching',
    Absurd: 'absurd',
    PassiveAggressive: 'passive_aggressive',
    Honest: 'honest'
} as const;
export type ListEndPagesToneEnum = typeof ListEndPagesToneEnum[keyof typeof ListEndPagesToneEnum];
