/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GeolocationRequest,
  GeolocationResponse,
} from '../models/index';
import {
    GeolocationRequestFromJSON,
    GeolocationRequestToJSON,
    GeolocationResponseFromJSON,
    GeolocationResponseToJSON,
} from '../models/index';

export interface GeolocateRequest {
    geolocationRequest: GeolocationRequest;
}

/**
 * 
 */
export class GeolocationApi extends runtime.BaseAPI {

    /**
     * Résoudre des coordonnées en informations géographiques
     */
    async geolocateRaw(requestParameters: GeolocateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeolocationResponse>> {
        if (requestParameters['geolocationRequest'] == null) {
            throw new runtime.RequiredError(
                'geolocationRequest',
                'Required parameter "geolocationRequest" was null or undefined when calling geolocate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/geo/resolve`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GeolocationRequestToJSON(requestParameters['geolocationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeolocationResponseFromJSON(jsonValue));
    }

    /**
     * Résoudre des coordonnées en informations géographiques
     */
    async geolocate(requestParameters: GeolocateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeolocationResponse> {
        const response = await this.geolocateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
