/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EndPage,
  ToggleHallOfFamePageRequest,
} from '../models/index';
import {
    EndPageFromJSON,
    EndPageToJSON,
    ToggleHallOfFamePageRequestFromJSON,
    ToggleHallOfFamePageRequestToJSON,
} from '../models/index';

export interface ToggleHallOfFamePageOperationRequest {
    id: string;
    toggleHallOfFamePageRequest: ToggleHallOfFamePageRequest;
}

/**
 * 
 */
export class HallOfFameApi extends runtime.BaseAPI {

    /**
     * Lister les pages du Hall of Fame
     */
    async listHallOfFamePagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<EndPage>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hall-of-fame`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EndPageFromJSON));
    }

    /**
     * Lister les pages du Hall of Fame
     */
    async listHallOfFamePages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<EndPage>> {
        const response = await this.listHallOfFamePagesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Ajouter ou retirer une page du Hall of Fame (admin only)
     */
    async toggleHallOfFamePageRaw(requestParameters: ToggleHallOfFamePageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling toggleHallOfFamePage().'
            );
        }

        if (requestParameters['toggleHallOfFamePageRequest'] == null) {
            throw new runtime.RequiredError(
                'toggleHallOfFamePageRequest',
                'Required parameter "toggleHallOfFamePageRequest" was null or undefined when calling toggleHallOfFamePage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/hall-of-fame/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ToggleHallOfFamePageRequestToJSON(requestParameters['toggleHallOfFamePageRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ajouter ou retirer une page du Hall of Fame (admin only)
     */
    async toggleHallOfFamePage(requestParameters: ToggleHallOfFamePageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.toggleHallOfFamePageRaw(requestParameters, initOverrides);
    }

}
