/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Opportunity } from '../models/index';
import { OpportunityFromJSON, OpportunityToJSON } from '../models/index';

export interface ListOpportunitiesRequest {
  type?: ListOpportunitiesTypeEnum;
}

/**
 *
 */
export class OpportunitiesApi extends runtime.BaseAPI {
  /**
   * Lister les opportunités après départ
   */
  async listOpportunitiesRaw(
    requestParameters: ListOpportunitiesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Opportunity>>> {
    const queryParameters: any = {};

    if (requestParameters['type'] != null) {
      queryParameters['type'] = requestParameters['type'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/opportunities`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(OpportunityFromJSON)
    );
  }

  /**
   * Lister les opportunités après départ
   */
  async listOpportunities(
    requestParameters: ListOpportunitiesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Opportunity>> {
    const response = await this.listOpportunitiesRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}

/**
 * @export
 */
export const ListOpportunitiesTypeEnum = {
  Job: 'job',
  Freelance: 'freelance',
  Event: 'event',
  SupportGroup: 'support_group',
} as const;
export type ListOpportunitiesTypeEnum =
  (typeof ListOpportunitiesTypeEnum)[keyof typeof ListOpportunitiesTypeEnum];
