/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SendContactFormRequest,
} from '../models/index';
import {
    SendContactFormRequestFromJSON,
    SendContactFormRequestToJSON,
} from '../models/index';

export interface SendContactFormOperationRequest {
    sendContactFormRequest: SendContactFormRequest;
}

/**
 * 
 */
export class PublicApi extends runtime.BaseAPI {

    /**
     * Envoyer un message de contact
     */
    async sendContactFormRaw(requestParameters: SendContactFormOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['sendContactFormRequest'] == null) {
            throw new runtime.RequiredError(
                'sendContactFormRequest',
                'Required parameter "sendContactFormRequest" was null or undefined when calling sendContactForm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/contact`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SendContactFormRequestToJSON(requestParameters['sendContactFormRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Envoyer un message de contact
     */
    async sendContactForm(requestParameters: SendContactFormOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.sendContactFormRaw(requestParameters, initOverrides);
    }

}
