/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReactionInput,
} from '../models/index';
import {
    ReactionInputFromJSON,
    ReactionInputToJSON,
} from '../models/index';

export interface ReactToPageRequest {
    id: string;
    reactionInput: ReactionInput;
}

/**
 * 
 */
export class ReactionsApi extends runtime.BaseAPI {

    /**
     * Réagir à une page
     */
    async reactToPageRaw(requestParameters: ReactToPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reactToPage().'
            );
        }

        if (requestParameters['reactionInput'] == null) {
            throw new runtime.RequiredError(
                'reactionInput',
                'Required parameter "reactionInput" was null or undefined when calling reactToPage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/end-pages/{id}/reactions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ReactionInputToJSON(requestParameters['reactionInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Réagir à une page
     */
    async reactToPage(requestParameters: ReactToPageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reactToPageRaw(requestParameters, initOverrides);
    }

}
