/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListTrendingHashtags200ResponseInner,
  SearchContent200Response,
} from '../models/index';
import {
    ListTrendingHashtags200ResponseInnerFromJSON,
    ListTrendingHashtags200ResponseInnerToJSON,
    SearchContent200ResponseFromJSON,
    SearchContent200ResponseToJSON,
} from '../models/index';

export interface SearchContentRequest {
    query: string;
    type?: SearchContentTypeEnum;
}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI {

    /**
     * Lister les hashtags tendance
     */
    async listTrendingHashtagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ListTrendingHashtags200ResponseInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/hashtags`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ListTrendingHashtags200ResponseInnerFromJSON));
    }

    /**
     * Lister les hashtags tendance
     */
    async listTrendingHashtags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ListTrendingHashtags200ResponseInner>> {
        const response = await this.listTrendingHashtagsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Rechercher des posts, utilisateurs ou hashtags
     */
    async searchContentRaw(requestParameters: SearchContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchContent200Response>> {
        if (requestParameters['query'] == null) {
            throw new runtime.RequiredError(
                'query',
                'Required parameter "query" was null or undefined when calling searchContent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['query'] != null) {
            queryParameters['query'] = requestParameters['query'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchContent200ResponseFromJSON(jsonValue));
    }

    /**
     * Rechercher des posts, utilisateurs ou hashtags
     */
    async searchContent(requestParameters: SearchContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchContent200Response> {
        const response = await this.searchContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchContentTypeEnum = {
    Post: 'post',
    User: 'user',
    Hashtag: 'hashtag'
} as const;
export type SearchContentTypeEnum = typeof SearchContentTypeEnum[keyof typeof SearchContentTypeEnum];
