/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetSubscriptionBenefits200Response,
  GetSubscriptionStatus200Response,
  Offer,
  SubscribeToOfferRequest,
  SubscriptionResponse,
} from '../models/index';
import {
    GetSubscriptionBenefits200ResponseFromJSON,
    GetSubscriptionBenefits200ResponseToJSON,
    GetSubscriptionStatus200ResponseFromJSON,
    GetSubscriptionStatus200ResponseToJSON,
    OfferFromJSON,
    OfferToJSON,
    SubscribeToOfferRequestFromJSON,
    SubscribeToOfferRequestToJSON,
    SubscriptionResponseFromJSON,
    SubscriptionResponseToJSON,
} from '../models/index';

export interface SubscribeToOfferOperationRequest {
    subscribeToOfferRequest: SubscribeToOfferRequest;
}

/**
 * 
 */
export class SubscriptionApi extends runtime.BaseAPI {

    /**
     * Récupérer les avantages de l\'abonnement de l\'utilisateur
     */
    async getSubscriptionBenefitsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSubscriptionBenefits200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/subscription/benefits`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSubscriptionBenefits200ResponseFromJSON(jsonValue));
    }

    /**
     * Récupérer les avantages de l\'abonnement de l\'utilisateur
     */
    async getSubscriptionBenefits(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSubscriptionBenefits200Response> {
        const response = await this.getSubscriptionBenefitsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Récupérer le statut d\'abonnement de l\'utilisateur connecté
     */
    async getSubscriptionStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSubscriptionStatus200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/subscription/status`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSubscriptionStatus200ResponseFromJSON(jsonValue));
    }

    /**
     * Récupérer le statut d\'abonnement de l\'utilisateur connecté
     */
    async getSubscriptionStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSubscriptionStatus200Response> {
        const response = await this.getSubscriptionStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Lister les offres disponibles
     */
    async listOffersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Offer>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/offers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OfferFromJSON));
    }

    /**
     * Lister les offres disponibles
     */
    async listOffers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Offer>> {
        const response = await this.listOffersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Souscrire à une offre avec paiement
     */
    async subscribeToOfferRaw(requestParameters: SubscribeToOfferOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionResponse>> {
        if (requestParameters['subscribeToOfferRequest'] == null) {
            throw new runtime.RequiredError(
                'subscribeToOfferRequest',
                'Required parameter "subscribeToOfferRequest" was null or undefined when calling subscribeToOffer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/offers/subscribe`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscribeToOfferRequestToJSON(requestParameters['subscribeToOfferRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Souscrire à une offre avec paiement
     */
    async subscribeToOffer(requestParameters: SubscribeToOfferOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionResponse> {
        const response = await this.subscribeToOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
