/* tslint:disable */
/* eslint-disable */
/**
 * Archeus Team dev build the app called --> TheEnd.Page
 * This app was produced to make your dream come true
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  Offer,
  SubscribeToOffer200Response,
  SubscribeToOfferRequest,
} from '../models/index';
import {
  OfferFromJSON,
  OfferToJSON,
  SubscribeToOffer200ResponseFromJSON,
  SubscribeToOffer200ResponseToJSON,
  SubscribeToOfferRequestFromJSON,
  SubscribeToOfferRequestToJSON,
} from '../models/index';

export interface SubscribeToOfferOperationRequest {
  subscribeToOfferRequest: SubscribeToOfferRequest;
}

/**
 *
 */
export class SubscriptionApi extends runtime.BaseAPI {
  /**
   * Lister les offres disponibles
   */
  async listOffersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Offer>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/offers`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(OfferFromJSON)
    );
  }

  /**
   * Lister les offres disponibles
   */
  async listOffers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Offer>> {
    const response = await this.listOffersRaw(initOverrides);
    return await response.value();
  }

  /**
   * Souscrire à une offre avec paiement
   */
  async subscribeToOfferRaw(
    requestParameters: SubscribeToOfferOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<SubscribeToOffer200Response>> {
    if (requestParameters['subscribeToOfferRequest'] == null) {
      throw new runtime.RequiredError(
        'subscribeToOfferRequest',
        'Required parameter "subscribeToOfferRequest" was null or undefined when calling subscribeToOffer().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('bearerAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/offers/subscribe`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: SubscribeToOfferRequestToJSON(
          requestParameters['subscribeToOfferRequest']
        ),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SubscribeToOffer200ResponseFromJSON(jsonValue)
    );
  }

  /**
   * Souscrire à une offre avec paiement
   */
  async subscribeToOffer(
    requestParameters: SubscribeToOfferOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<SubscribeToOffer200Response> {
    const response = await this.subscribeToOfferRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
